### ISSUE TITLE
Problems with installing

### ISSUE THREAD

**Issue by StarrKiss** [torvic9/plasmafox#10]
A: How do I install the built, release versions?
B: My built from source version refuses to launch, saying that it can't find libicui18n.so.64, when I supply that, it gives me a similar error of libicuuc, and when I supply that, it gives me an unknown symbol in XPCOM error.

**Comment by torvic9** [comment]
A: `pacman -U`
B: You have to rebuild it. Current icu version in Manjaro testing is 65.1. See output of `pacman -Qi icu`.
