### ISSUE TITLE
No global menu.

### ISSUE THREAD

**Issue by sirakai-pc** [torvic9/plasmafox#12]
I compiled it and it semms to me like a normal 'archlabs' firefox. It has no global menu, and it seems to have microbugs(like about:preferences#privacy = about:preferences#search). 
I recorded the screen and uploaded in vimeo. It's a bit buggy but its understandable:
[https://vimeo.com/403986024](url)

**Comment by torvic9** [comment]
Do you have [kplasmafoxhelper](https://github.com/torvic9/kplasmafoxhelper) installed?

> and it seems to have microbugs(like about:preferences#privacy = about:preferences#search).

Thanks for noticing. I'll have a look at it but I don't know when.

**Comment by torvic9** [comment]
The bug is referenced here: https://bugzilla.mozilla.org/show_bug.cgi?id=1625457
I'll see if I can update it for 74.0.1.
EDIT: fixed.

**Comment by sirakai-pc** [comment]
I recompiled it but still there's not global menu functionality in plasmafox-75.0-2. I also installed kplasmafoxhelper.

**Comment by torvic9** [comment]
Someone else has to confirm. I do not use global menus, and I currently do not have access to a KDE/Plasma computer.

**Comment by sirakai-pc** [comment]
But I sent you the video. There's a proof. People install plasmafox on kde principally for that. It's a shame that it doesn't work(archlabs+kde)21:51, 17 aprile 2020, torvic9 <notifications@github.com>:
Someone else has to confirm. I do not use global menus, and I currently do not have access to a KDE/Plasma computer.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by torvic9** [comment]
Do you have `appmenu-gtk-module` and `libdbusmenu-{qt5,gtk3}` installed?
It works here (I think).

> People install plasmafox on kde principally for that.

Not sure about that. Personally I'm only interested in the file dialogs and I never use global menu.
Anyway, please report back.

**Comment by sirakai-pc** [comment]
I didn't, now it works. Thank you.15:01, 19 aprile 2020, torvic9 <notifications@github.com>:
Do you have appmenu-gtk-module and libdbusmenu-{qt5,gtk3} installed?
It works here (I think).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile
