### ISSUE TITLE
[Request] Make available on AUR

### ISSUE THREAD

**Issue by baduhai** [torvic9/plasmafox#13]
Very few tweaks would be needed to have the PKGBUILD fit the AUR guidelines, why not have an AUR package?

**Comment by torvic9** [comment]
1. I don't consider this project to be of good enough quality to make it available to a larger audience (I'm not a coder or developer).
2. I don't currently have any Arch installation, and the 'A' in AUR stands for Arch - could lead to incompatibilities with system libs which are not necessarily on the same version as Manjaro testing.
3. We have `firefox-kde-opensuse` in AUR which is similar and provides similar functionality.
4. Most people (especially those on older hardware) will probably use the provided binaries as the build time is rather long - count an hour or so on a hexa-core machine.

I hope this helps.

**Comment by baduhai** [comment]
I see, your points make sense. It's a shame because it seems that firefox-kde-opensuse has been abandoned on the aur, or at least it takes so long to update that's it's not an option for me to use.
