### ISSUE TITLE
plasmafox failing to build on chaotic-aur repo

### ISSUE THREAD

**Issue by ghost** [torvic9/plasmafox#14]
so we have been building plasmafox daily for a long time on chaotic-aur repo.now it is not building
so please make pkgbuild changes so it will work on clean chroot

here is the log
https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_daily/plasmafox.log

**Comment by torvic9** [comment]
See https://github.com/torvic9/plasmafox/issues/11

Will be changed when clang10 hits the repos. 
In the meantime, change the paths pointing to clang as mentioned in the issue thread above.
N.B.: the provided binaries are built in a clean environment (systemd container).

**Comment by torvic9** [comment]
Oh, it is now in Arch staging. I changed the paths back to system clang again.
Untested, please report back.

**Comment by baduhai** [comment]
Looks like it's fixed, I managed to install plasmafox from chaotic-aur today.
