### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by wazlecracker** [torvic9/plasmafox#17]
Since updating, nothing happens when trying to launch via plasma icon. This is the error when trying to launch from CLI:
```
XPCOMGlueLoad error for file /usr/lib/plasmafox/libxul.so:
libicui18n.so.67: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
On Manjaro KDE, plasma 5.18.4.1-1
Kernel 5.6.8-1
Installed from Chaotic-AUR. v75.0-3

**Comment by torvic9** [comment]
I do not support Chaotic AUR, they have to rebuild against new icu.

Use the binaries that I provide, they work. Any other binaries are not supported.

**Comment by wazlecracker** [comment]
Fair enough and understood. How does one go about contacting them about this?

**Comment by torvic9** [comment]
I don't know, maybe @librewish?

**Comment by wazlecracker** [comment]
Found their repo and submitted an issue.

**Comment by ghost** [comment]
okay i will issue an rebuild

**Comment by ghost** [comment]
the rebuilt package. now in repo.
since no pkgrel was bumped you need to clear the cache and redownload the package
