### ISSUE TITLE
Improper file handling

### ISSUE THREAD

**Issue by wazlecracker** [torvic9/plasmafox#18]
On latest Manjaro KDE, stable branch, kernel 5.6.11-1, plasmafox 76.0.1

When clicking on a file to download, if the option to open the file with a relevant program is chosen, the file opens in gwenview no matter the program chosen to handle the file in plasmafox in this menu:
![image](https://user-images.githubusercontent.com/45174508/82233734-fa43ba80-991f-11ea-96c3-23f6820f18d2.png)

When I do the same in standard Firefox, it's handled properly.

**Comment by torvic9** [comment]
Hi, thanks for reporting.
Unfortunately, I currently don't have access to my KDE machine.
Would be great if someone else could confirm this issue. I guess it's some MIME issue.

(Not related to the issue, but important: I only support testing branch.)

**Comment by wazlecracker** [comment]
>(Not related to the issue, but important: I only support testing branch.)

Understood. What logs could I give you to help you understand what's going on?

**Comment by torvic9** [comment]
You could run `plasmafox` from the terminal and check for any error message when clicking on "open with". (There could be a few unrelated errors or warnings as well).
Also make sure you have latest kplasmafoxhelper installed.

I'll see if I can check this tomorrow, and then I'll get back to you.

**Comment by wazlecracker** [comment]
Nothing pops up when I open a file, however the follow does when launching plasmafox:
```
Gtk-Message: 13:49:18.127: Failed to load module "appmenu-gtk-module"
Gtk-Message: 17:49:18.387: Failed to load module "appmenu-gtk-module"

(Plasmafox:785882): LIBDBUSMENU-GTK-CRITICAL **: 17:49:18.591: dbusmenu_menuitem_property_set_shortcut: assertion 'gtk_accelerator_valid(key, modifier)' failed

(Plasmafox:785882): GLib-GIO-WARNING **: 17:49:18.760: /etc/xdg/kde-mimeapps.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
```

**Comment by torvic9** [comment]
I did a quick check and I cannot confirm this here.
Clicked on a .xz file, the dialog had "Ark" chosen as program, and the file did open in Ark.

**Comment by wazlecracker** [comment]
Yea, I don't know what happened, but the issue strangely went away.
