### ISSUE TITLE
Smoth scroll via JS

### ISSUE THREAD

**Issue by sr-tream** [torvic9/plasmafox#19]
Does not work property `behavior: 'smooth'` in `window.scrollTo`. In original Firefox it work.

**Comment by torvic9** [comment]
Sorry I don't really understand what you mean.
Can you please be more precise, and maybe include steps to reproduce?
If it's a coding issue with Javascript, then I probably cannot help, as I'm not a coder.

**Comment by sr-tream** [comment]
Open any site with button "Scroll to top" or install extension for get that button on all sites. And click this button when viewport on bottom -> page scrolled without smoothing.

**Comment by torvic9** [comment]
Please give an example of such a site.
I tried the "to top" button on heise.de, jumps immediately to top without any scrolling.
Do you use any custom CSS or `layout.css*` settings?
EDIT: I will also try to push v77.0 soon.

**Comment by sr-tream** [comment]
https://www.blast.hk/ After mouse scroll it show buttons "to top" and "to bottom" in right-bottom part of viewport

**Comment by torvic9** [comment]
Since I don't really know if this issue persists, I'm closing this now.
