### ISSUE TITLE
Icons in Tabs.

### ISSUE THREAD

**Issue by ben2talk** [torvic9/plasmafox#20]
Manjaro forum has a white square instead of the normal icon shown in firefox etc.

**Comment by ben2talk** [comment]
The icon appears, then is replaced with a white square.

**Comment by ben2talk** [comment]
![TabIcons](https://user-images.githubusercontent.com/6983154/83952531-fde4a600-a828-11ea-87e5-536660db2bae.png)

**Comment by torvic9** [comment]
Looks fine here:

![Screenshot_20200607_214016](https://user-images.githubusercontent.com/25117231/83978500-67cb8100-a8f7-11ea-88ac-a946caeae0b0.png)

I did however see that white square in the past. No idea where it comes from.

**Comment by torvic9** [comment]
I'm closing this as it is probably not related to Plasmafox, feel free to reopen if you have more details.
