### ISSUE TITLE
Global menu (in Latte)

### ISSUE THREAD

**Issue by SethStormR** [torvic9/plasmafox#22]
Greetings,

I sometimes expirence that Global menu dissapearing. I have to log out and login again to get Global Menu.

regards
Storm

**Comment by torvic9** [comment]
Hi,

Does global menu only disappear with Plasmafox?
Anything in your logs/journal?
Personally I don't use global menus or Latte.

**Comment by SethStormR** [comment]
I can't re-make the disappearing. It seems to be a one time happening.

**Comment by SethStormR** [comment]
I found out that if I click  on the windows bar the global menu appear but the "close and minimize" button disappear. 
![Screenshot_20200725_033333](https://user-images.githubusercontent.com/60283532/88446197-39aeeb80-ce28-11ea-8734-8caf0828e2f5.png)
![Screenshot_20200725_033417](https://user-images.githubusercontent.com/60283532/88446202-3fa4cc80-ce28-11ea-9d43-3c1ff0f4b093.png)

**Comment by torvic9** [comment]
Maybe related to #16

**Comment by Aleksanaa** [comment]
That's not related to latte.

**Comment by torvic9** [comment]
Button issue should be fixed now (see #16 )
Closed.
