### ISSUE TITLE
Activate Sync

### ISSUE THREAD

**Issue by ShalokShalom** [torvic9/plasmafox#25]
Hi, I like to use Sync with your software. 
Can I just flip a switch or did you remove the code?

Thanks a lot in advance. :)

**Comment by torvic9** [comment]
Hi, sorry for the late response.
I don't use Sync, but it should be enough to enable fxaccounts in about:config.

**Comment by ShalokShalom** [comment]
Oh, nice. :)

**Comment by torvic9** [comment]
So does it work for you now?

**Comment by ShalokShalom** [comment]
I didn't try yet.

**Comment by torvic9** [comment]
Closed. Feel free to reopen if the problem is not fixed.
