### ISSUE TITLE
Fail to Launch - Couldn't Load XPCOM

### ISSUE THREAD

**Issue by lordsolomon** [torvic9/plasmafox#26]
Hey! Looks similar to #17, plasmafox fails to launch, and when run from cli prints:

```
XPCOMGlueLoad error for file /usr/lib/plasmafox/libxul.so:
libaom.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

AOM is installed, Plasmafox is installed from latest git release --not the AUR.

System is running EndeavourOS.

**Comment by torvic9** [comment]
Either rebuild  plasmafox or downgrade `aom`.
Errors like these are almost always due to recent library updates.
