### ISSUE TITLE
DRM support?

### ISSUE THREAD

**Issue by StarrKiss** [torvic9/plasmafox#9]
Hey, I would love to watch netflix on Plasmafox, but can't as DRM is disabled. How do I re-enable it? I know you can find some way to enable at compile.

**Comment by StarrKiss** [comment]
Hello, I edited the mozconfig but can't get it to compile, keep getting an error in build() about nss missing or being behind version but it is installed and on latest version

**Comment by StarrKiss** [comment]
![image](https://user-images.githubusercontent.com/13007697/70196209-eef92b80-16ff-11ea-954a-05bbc215d792.png)
I had to disable PGP and SHA checks because it kept marking my edited mozconfig as invalid

**Comment by torvic9** [comment]
I do not support DRM.
To reenable, remove `--disable-webeme` from mozconfig.

You do not have to disable GPG and SHA checks.
For GPG, import the Mozilla pubkey into your keyring.
When you modify any files from sources array (like mozconfig), you have to update the checksums either manually or with `updpkgsums`.

You should be on Manjaro testing branch.
Also note that there is no 71.0 tagged release yet.
